admin:
    path:     /
    defaults: { _controller: AdminBundle:Index:index }

admin_add_product:
    path:     /add-product
    defaults: { _controller: AdminBundle:Products:add }
admin_all_products:
    path:     /all-products
    defaults: { _controller: AdminBundle:Products:all}
admin_view_product:
    path:     /product/{id}
    defaults: { _controller: AdminBundle:Products:view }
    requirements:
        id:  \d+
admin_delete_product:
    path:     /delete/product/{id}
    defaults: { _controller: AdminBundle:Products:delete }
    requirements:
        id:  \d+
admin_categories:
    path:     /categories
    defaults: { _controller: AdminBundle:Categories:add }
admin_delete_category:
    path: /delete/category/{id}
    defaults: { _controller: AdminBundle:Categories:delete }
    requirements:
        id:  \d+

admin_products_category:
    path: /products/category/{id}
    defaults: {_controller: AdminBundle:Categories:allproducts}
    requirements:
        id: \d+