<?php

namespace Ecommerce\AccountBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsRepository extends EntityRepository
{
	public function findInfosUser() {
		$em = $this->getEntityManager()->createQueryBuilder();
		$em->select(array('u'))
			->from('AccountBundle:Account', 'u')
		// 	->join('u.adresses', 'a', 'WITH', $em->expr()->in('c.id', $id));
		// $result = $em->getQuery()->execute();
		return $result;

	}
}
