<?php

namespace Ecommerce\AccountBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends EntityRepository
{

	public function findAdresses($type, $id) {
		return $query = $this->createQueryBuilder('a')
		->select('a')
		->join('a.account', 'c')
		->where('a.type = :type')
		->setParameter('type', $type )
		->andWhere('c.id = :id')
		->setParameter('id', $id )

		->getQuery()
		->execute();


	}
}
