<?php

namespace Proxies\__CG__\Ecommerce\ProductBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \Ecommerce\ProductBundle\Entity\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'id', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'idParent', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'name', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'preview', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'createdAt', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'updatedAt', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'medias', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'featureNames', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'products_cat', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'products');
        }

        return array('__isInitialized__', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'id', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'idParent', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'name', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'preview', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'createdAt', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'updatedAt', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'medias', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'featureNames', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'products_cat', '' . "\0" . 'Ecommerce\\ProductBundle\\Entity\\Category' . "\0" . 'products');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdParent($idParent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdParent', array($idParent));

        return parent::setIdParent($idParent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdParent', array());

        return parent::getIdParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedias($medias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedias', array($medias));

        return parent::setMedias($medias);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedias', array());

        return parent::getMedias();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\Ecommerce\ProductBundle\Entity\Product $products)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', array($products));

        return parent::addProduct($products);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\Ecommerce\ProductBundle\Entity\Product $products)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', array($products));

        return parent::removeProduct($products);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', array());

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function addMedia(\Ecommerce\ProductBundle\Entity\Media $medias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedia', array($medias));

        return parent::addMedia($medias);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedia(\Ecommerce\ProductBundle\Entity\Media $medias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedia', array($medias));

        return parent::removeMedia($medias);
    }

    /**
     * {@inheritDoc}
     */
    public function addFeatureName(\Ecommerce\ProductBundle\Entity\FeatureName $featureNames)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFeatureName', array($featureNames));

        return parent::addFeatureName($featureNames);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFeatureName(\Ecommerce\ProductBundle\Entity\FeatureName $featureNames)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFeatureName', array($featureNames));

        return parent::removeFeatureName($featureNames);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeatureNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeatureNames', array());

        return parent::getFeatureNames();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateddAt($updateddAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateddAt', array($updateddAt));

        return parent::setUpdateddAt($updateddAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateddAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateddAt', array());

        return parent::getUpdateddAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreview($preview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreview', array($preview));

        return parent::setPreview($preview);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreview', array());

        return parent::getPreview();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductsCat(\Ecommerce\ProductBundle\Entity\Product $productsCat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductsCat', array($productsCat));

        return parent::addProductsCat($productsCat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductsCat(\Ecommerce\ProductBundle\Entity\Product $productsCat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductsCat', array($productsCat));

        return parent::removeProductsCat($productsCat);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductsCat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductsCat', array());

        return parent::getProductsCat();
    }

}
