Ecommerce\ProductBundle\Entity\Media:
    type: entity
    table: medias
    repositoryClass: Ecommerce\ProductBundle\Repository\MediaRepository
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: medias
            cascade: ["persist", 'remove']
            joinColumn:
                name: category_id
                referencedColumnName: id
        productDerived:
            targetEntity: ProductDerived
            inversedBy: medias
            cascade: ["persist", 'remove']
            joinColumn:
                name: product_derived_id
                referencedColumnName: id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        filename:
            type: string
            nullable: false
            length: 255
            fixed: false
        type:
            type: string
            nullable: false
            length: 255
            fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        path:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
