Ecommerce\ProductBundle\Entity\ProductDerived:
    type: entity
    table: products_derived
    repositoryClass: Ecommerce\ProductBundle\Repository\ProductDerivedRepository
    manyToOne:
        product:
            targetEntity: Product
            inversedBy: productsDerived
            column: product_id
            foreignTable: products
            foreignReference: id
            cascade: ["persist",'remove']
    oneToMany:
        medias:
            targetEntity: Media
            mappedBy: productDerived
            cascade: ["persist", 'remove']
            joinColumn:
                name: product_derived_id
                referencedColumnName: id
        featureDerivedValues:
            targetEntity: FeatureDerivedValue
            mappedBy: productDerived
            cascade: ["persist", 'remove']

    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nameDerived:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: name_derived
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        weight:
            type: float
            nullable: false
            precision: 10
            scale: 0
        status:
            type: integer
            nullable: false
            unsigned: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks: {  }
