<?php

namespace Ecommerce\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{

	public function findByUser($id) {
		return $query = $this->createQueryBuilder('com')
		->select(['com', 'adr'])
		->join('com.adresse', 'adr')
		->join('adr.account', 'acc')

		->where('adr.account = :id')

		->setParameter('id',$id )
		->getQuery()
		->execute();
	}
}
