<?php

namespace Ecommerce\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends EntityRepository
{
	public function findByDerived($id) {
		return $query = $this->createQueryBuilder('pan')
		->select(['pan','der'])
		->join('pan.productsDerived', 'der')

		->where('pan.commande = :id')

		->setParameter('id',$id )
		->getQuery()
		->execute();
	}
}
