<?php

namespace Ecommerce\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ProductRepository extends EntityRepository
{
	public function findByCategories($id) {
		$em = $this->getEntityManager()->createQueryBuilder();
		$em->select(array('p'))
			->from('ProductBundle:Product', 'p')
			->join('p.categories', 'c', 'WITH', $em->expr()->in('c.id', $id));
		$result = $em->getQuery()->execute();
		return $result;
	}

}
