<?php

namespace Ecommerce\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductDerivedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDerivedRepository extends EntityRepository
{

	public function findByProduct($id) {
		return $query = $this->createQueryBuilder('der')
		->select('der')
		->where('der.product = :id')

		->setParameter('id',$id )
		->getQuery()
		->execute();
	}
}
