admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

ecommerce_account:
    resource: "@AccountBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Index:index }
