security:
    providers:
        your_db_provider:
            entity:
                class:  AccountBundle:Accounts
                property: username

    encoders:
        Ecommerce\AccountBundle\Entity\Accounts:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            http_basic: ~
            provider: your_db_provider
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                check_path: /login
                login_path: /login
            logout:
                path: /logout
        default:
            anonymous: ~
            http_basic: ~
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }