login:
    path:     /login
    defaults: { _controller: AccountBundle:Security:login }

login_check:
    path:     /login
    defaults: { _controller: AccountBundle:Security:login }

registration:
    path:     /registration
    defaults: { _controller: AccountBundle:Security:registration }

logout:
    path:     /logout
