login:
    path:     /login
    defaults: { _controller: AccountBundle:Security:login }

ecommerce_account_registration:
    path:     /registration
    defaults: { _controller: AccountBundle:Auth:registration }

ecommerce_account_deconnexion:
    path:     /deconnexion
    defaults: { _controller: AccountBundle:Auth:deconnexion }

ecommerce_account_account:
    path:     /account
    defaults: { _controller: AccountBundle:User:account }